# Generated by Django 3.1.4 on 2020-12-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Sizes',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
